name: Terraform Apply Production
on:
  push:
    tags:
      - "*"
jobs:
  terraform-apply:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    timeout-minutes: 60
    env:
      PROJECT_ID: ${{ secrets.PROJECT_ID_PROD }}
      WORKLOAD_IDENTITY_PROVIDER: ${{ secrets.WORKLOAD_IDENTITY_PROVIDER_PROD }}
      SERVICE_ACCOUNT: ${{ secrets.SERVICE_ACCOUNT_PROD }}
      BILLING_ACCOUNT: ${{ secrets.BILLING_ACCOUNT_PROD }}
      BUCKET_NAME: ${{ secrets.BUCKET_NAME_PROD }}
      ANDROID_PACKAGE_NAME: ${{ secrets.ANDROID_PACKAGE_NAME_PROD }}
      IOS_BUNDLE_ID: ${{ secrets.IOS_BUNDLE_ID_PROD }}
      GCP_PRINCIPAL_MIDORI: ${{ secrets.GCP_PRINCIPAL_MIDORI }}
      GCP_PRINCIPAL_SATORU: ${{ secrets.GCP_PRINCIPAL_SATORU }}
      GCP_PRINCIPAL_COBO: ${{ secrets.GCP_PRINCIPAL_COBO }}
      FIREBASE_ADMINSDK_SERVICE_ACCOUNT: ${{ secrets.FIREBASE_ADMINSDK_SERVICE_ACCOUNT_PROD }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v1'
        with:
          workload_identity_provider: ${{ env.WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ env.SERVICE_ACCOUNT }}
          create_credentials_file: true
          export_environment_variables: true
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
      - name: Check Terraform Format
        run: terraform fmt -check -diff -recursive
      - name: Initialize Terraform
        run: terraform init -input=false -backend-config="bucket=${{ env.BUCKET_NAME }}"
      - name: Run Terraform Plan
        run: >
          terraform plan 
          -lock-timeout=120s 
          -var=project_id=${{ env.PROJECT_ID }} 
          -var=project_name=${{ env.PROJECT_ID }} 
          -var=billing_account=${{ env.BILLING_ACCOUNT }} 
          -var=android_package_name=${{ env.ANDROID_PACKAGE_NAME }} 
          -var=ios_bundle_id=${{ env.IOS_BUNDLE_ID }}
          -var=gcp_principal_midori=${{ env.GCP_PRINCIPAL_MIDORI }}
          -var=gcp_principal_satoru=${{ env.GCP_PRINCIPAL_SATORU }}
          -var=gcp_principal_cobo=${{ env.GCP_PRINCIPAL_COBO }}
          -var=firebase_adminsdk_service_account=${{ env.FIREBASE_ADMINSDK_SERVICE_ACCOUNT }}

      - name: Run Terraform Apply
        run: >
          terraform apply -auto-approve 
          -lock-timeout=120s 
          -var=project_id=${{ env.PROJECT_ID }} 
          -var=project_name=${{ env.PROJECT_ID }} 
          -var=billing_account=${{ env.BILLING_ACCOUNT }} 
          -var=android_package_name=${{ env.ANDROID_PACKAGE_NAME }} 
          -var=ios_bundle_id=${{ env.IOS_BUNDLE_ID }}
          -var=gcp_principal_midori=${{ env.GCP_PRINCIPAL_MIDORI }}
          -var=gcp_principal_satoru=${{ env.GCP_PRINCIPAL_SATORU }}
          -var=gcp_principal_cobo=${{ env.GCP_PRINCIPAL_COBO }}
          -var=firebase_adminsdk_service_account=${{ env.FIREBASE_ADMINSDK_SERVICE_ACCOUNT }}